#!/bin/bash --login
#PBS -N sphere
#PBS -A e283-lianhua
#PBS -l select=256
#PBS -l walltime=00:20:00
#PBS -m abe
#PBS -M zhulianhua121@gmail.com

# Switch to current working directory
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
export PATH=$PATH:/work/e283/e283/lhzhu/mpi_dvm3d/build
# Run the serial program
date
aprun -n 512  -N 2 -S 1 -d 12 dvm3d.x > log
date
